# =============================================================
#  EcoSort AI — CNN Training Script
#  train_cnn.py
#
#  Trains a ResNet18 CNN classifier on YOLO-cropped waste images
#  This is the classification refinement layer of the hybrid system.
#
#  Usage:
#    python train_cnn.py
# =============================================================

import os
import sys
import time
import copy
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, models, transforms

# ─────────────────────────────────────────────
#  CONFIG
# ─────────────────────────────────────────────

# Path to cropped images generated by generate_crops.py
CROPS_FOLDER = r"C:\Users\Victus\Documents\GitHub\TrashDetect\CNN_Dataset"

# Where to save the trained CNN model
CNN_OUTPUT_PATH = r"C:\Users\Victus\Documents\GitHub\TrashDetect\runs\cnn\ecosort_cnn_v1.pt"

# Training config
NUM_EPOCHS     = 30
BATCH_SIZE     = 32
LEARNING_RATE  = 0.001
VALIDATION_SPLIT = 0.2   # 80% train / 20% validation

# CNN input size (must match generate_crops.py CNN_SIZE)
CNN_SIZE = 224

# Classes (must match YOLO class order)
CLASSES = ['cardboard', 'glass', 'metal', 'paper', 'plastic']

# ─────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────

def train_cnn():

    # ── Device ──────────────────────────────
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Using device: {device}")
    if device.type == "cuda":
        print(f"[INFO] GPU: {torch.cuda.get_device_name(0)}\n")

    # ── Data transforms ─────────────────────
    # Training: augmentation to improve generalisation
    train_transform = transforms.Compose([
        transforms.Resize((CNN_SIZE, CNN_SIZE)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(15),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406],
                             [0.229, 0.224, 0.225])
    ])

    # Validation: no augmentation
    val_transform = transforms.Compose([
        transforms.Resize((CNN_SIZE, CNN_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406],
                             [0.229, 0.224, 0.225])
    ])

    # ── Load dataset ─────────────────────────
    print(f"[INFO] Loading dataset from: {CROPS_FOLDER}")
    if not Path(CROPS_FOLDER).exists():
        print(f"[ERROR] CNN_Dataset folder not found.")
        print(f"        Run generate_crops.py first.")
        sys.exit(1)

    full_dataset = datasets.ImageFolder(CROPS_FOLDER)
    print(f"[INFO] Classes found: {full_dataset.classes}")
    print(f"[INFO] Total images : {len(full_dataset)}\n")

    # Validate class order matches YOLO
    if full_dataset.classes != sorted(CLASSES):
        print(f"[WARNING] Class order mismatch.")
        print(f"          Found  : {full_dataset.classes}")
        print(f"          Expected: {sorted(CLASSES)}")

    # ── Train / val split ────────────────────
    val_size   = int(len(full_dataset) * VALIDATION_SPLIT)
    train_size = len(full_dataset) - val_size

    train_dataset, val_dataset = random_split(
        full_dataset,
        [train_size, val_size],
        generator=torch.Generator().manual_seed(42)
    )

    # Apply different transforms to each split
    train_dataset.dataset.transform = train_transform
    val_dataset.dataset.transform   = val_transform

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2)
    val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

    print(f"[INFO] Training images  : {train_size}")
    print(f"[INFO] Validation images: {val_size}\n")

    # ── Build ResNet18 model ─────────────────
    print("[INFO] Building ResNet18 model with pretrained ImageNet weights...")
    model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

    # Replace final fully connected layer for our 5 classes
    num_features       = model.fc.in_features
    model.fc           = nn.Linear(num_features, len(CLASSES))
    model              = model.to(device)

    print(f"[INFO] Model ready. Output classes: {len(CLASSES)}\n")

    # ── Loss and optimiser ───────────────────
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

    # ── Training loop ────────────────────────
    best_model_weights = copy.deepcopy(model.state_dict())
    best_val_acc       = 0.0
    start_time         = time.time()

    print(f"{'Epoch':<8} {'Train Loss':<14} {'Train Acc':<14} {'Val Loss':<14} {'Val Acc':<12}")
    print("-" * 62)

    for epoch in range(NUM_EPOCHS):

        # ── Train phase ──────────────────────
        model.train()
        train_loss = 0.0
        train_correct = 0

        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss    = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            train_loss    += loss.item() * inputs.size(0)
            _, preds       = torch.max(outputs, 1)
            train_correct += (preds == labels).sum().item()

        train_loss /= train_size
        train_acc   = train_correct / train_size

        # ── Validation phase ─────────────────
        model.eval()
        val_loss    = 0.0
        val_correct = 0

        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs        = model(inputs)
                loss           = criterion(outputs, labels)
                val_loss      += loss.item() * inputs.size(0)
                _, preds       = torch.max(outputs, 1)
                val_correct   += (preds == labels).sum().item()

        val_loss /= val_size
        val_acc   = val_correct / val_size

        scheduler.step()

        # Save best model
        if val_acc > best_val_acc:
            best_val_acc       = val_acc
            best_model_weights = copy.deepcopy(model.state_dict())
            best_marker        = " ← best"
        else:
            best_marker = ""

        print(f"{epoch+1:<8} {train_loss:<14.4f} {train_acc:<14.1%} {val_loss:<14.4f} {val_acc:<12.1%}{best_marker}")

    # ── Save best model ──────────────────────
    elapsed = time.time() - start_time
    model.load_state_dict(best_model_weights)

    Path(CNN_OUTPUT_PATH).parent.mkdir(parents=True, exist_ok=True)

    # Save model with class names for inference
    torch.save({
        "model_state_dict": model.state_dict(),
        "classes":          full_dataset.classes,
        "num_classes":      len(CLASSES),
        "cnn_size":         CNN_SIZE,
        "best_val_acc":     best_val_acc,
    }, CNN_OUTPUT_PATH)

    print(f"\n{'=' * 50}")
    print(f"  CNN TRAINING COMPLETE")
    print(f"{'=' * 50}")
    print(f"  Best validation accuracy : {best_val_acc:.1%}")
    print(f"  Training time            : {elapsed/60:.1f} minutes")
    print(f"  Model saved to           : {CNN_OUTPUT_PATH}")
    print(f"{'=' * 50}")
    print(f"\n[INFO] Next step: update detect.py to use hybrid pipeline\n")


if __name__ == "__main__":
    train_cnn()
